version: "3"

services:
  main:
    image: nginx
    restart: always
    volumes:
    - ./configuration:/etc/nginx/conf.d:ro
    - ./webroot:/usr/share/nginx/html:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
    - {{ '{}:80:80'.format(address) if address is defined else '80:80' }}
    - {{ '{}:443:443'.format(address) if address is defined else '443:443' }}
