version: "3"

services:
  nginx:
    image: nginx
    volumes:
    - ./configuration:/etc/nginx/conf.d:ro
    - ./letsencrypt:/etc/letsencrypt:ro
    - ./webroot:/usr/share/nginx/html:ro
    ports:
    - {{ '{}:80:80'.format(address) if address is defined else '80:80' }}
    - {{ '{}:443:443'.format(address) if address is defined else '443:443' }}
  certbot:
    build:
      context: https://github.com/julmb/certbot.git#main
      args:
        tag: {{ certbot_architecture[ansible_architecture] }}-latest
    volumes:
    - ./letsencrypt:/etc/letsencrypt
    - ./webroot:/webroot
