version: "3"

services:
  main:
    image: jellyfin/jellyfin
    restart: always
    volumes:
    - ./config:/config
    - ./cache:/cache
    - /mnt/pool1/files/user1:/media/user1:ro
    - /mnt/pool1/files/user2:/media/user2:ro
    ports:
    - {{ '{}:80:8096'.format(address) if address is defined else '80:8096' }}
