- name: repositories directory
  ansible.builtin.file:
    path: .kodi/addons
    state: directory
- name: jellyfin repository
  ansible.builtin.unarchive:
    src: https://kodi.jellyfin.org/repository.jellyfin.kodi.zip
    dest: .kodi/addons/
    remote_src: true
- name: youtube addon api keys
  ansible.builtin.template:
    src: api_keys.json
    dest: .kodi/userdata/addon_data/plugin.video.youtube/
