- name: package facts
  ansible.builtin.package_facts:
- name: check raspberrypi-net-mods
  ansible.builtin.set_fact: { fresh: "{{ 'raspberrypi-net-mods' in ansible_facts.packages }}" }

- name: interfaces
  ansible.builtin.copy: { src: interfaces.cfg, dest: /etc/network/interfaces }
  when: fresh
- name: plain network
  ansible.builtin.apt: { name: [dhcpcd, dhcpcd5, resolvconf, openresolv], state: absent, purge: yes, autoremove: yes }
  when: fresh
- name: reboot
  ansible.builtin.reboot:
  when: fresh
