- name: download image
  ansible.builtin.get_url: { url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.3.0-amd64-netinst.iso, dest: ~/preseed/debian-11.3.0-amd64-netinst.iso }
- name: add preseed
  ansible.builtin.copy: { src: preseed.cfg, dest: ~/preseed/ }
- name: add grub configurtaion
  ansible.builtin.copy: { src: grub.cfg, dest: ~/preseed/ }
- name: repack iso
  ansible.builtin.command: |
    xorriso
    -indev ~/preseed/debian-11.3.0-amd64-netinst.iso
    -outdev ~/preseed/out.iso
    -boot_image any keep
    -map ~/preseed/preseed.cfg preseed.cfg
    -map ~/preseed/grub.cfg boot/grub/grub.cfg
