services:
  database:
    image: ibmcom/db2
    restart: unless-stopped
    volumes: [./data:/database]
    ports: [{{ forward | default(50000) }}:50000]
    cap_add: [IPC_OWNER]
    environment:
      LICENSE: {{ license }}
      DB2INSTANCE: {{ instance }}
      DB2INST1_PASSWORD: {{ password }}
      DBNAME: {{ database }}
