- name: no dhcpcd
  ansible.builtin.package: { name: [dhcpcd, dhcpcd5], state: absent }
  notify: restart networking
- name: network base
  ansible.builtin.copy: { src: interfaces.cfg, dest: /etc/network/interfaces }
  notify: restart networking
- name: network loopback
  ansible.builtin.copy: { src: lo.cfg, dest: /etc/network/interfaces.d/ }
  notify: restart networking
- name: network interfaces
  ansible.builtin.template: { src: interface.cfg, dest: "/etc/network/interfaces.d/{{ item.key }}.cfg" }
  notify: restart networking
  loop: "{{ interfaces | dict2items }}"
