- name: base configuration
  ansible.builtin.copy: { src: base.cfg, dest: /etc/network/interfaces }
  notify: restart networking service
- name: enp3s0 configuration
  ansible.builtin.copy: { src: enp3s0.cfg, dest: /etc/network/interfaces.d/ }
  notify: restart networking service
