- name: ssh
  hosts: host1
  become: true
  tasks:
  - name: set listen address
    ansible.builtin.lineinfile: { path: /etc/ssh/sshd_config, regexp: "^#?ListenAddress ", line: ListenAddress 192.168.0.11 }
    notify: restart service
  handlers:
  - name: restart service
    ansible.builtin.service: { name: ssh, state: restarted }
