version: "3"

services:
  main:
    image: drone/drone
    restart: unless-stopped
    volumes: [./data:/data]
    ports:
    - {{ '{}:80:80'.format(address) if address is defined else '80:80' }}
    environment:
      DRONE_SERVER_HOST: {{ drone.url }}
      DRONE_RPC_SECRET: {{ drone.rpc_secret }}
      DRONE_GITEA_SERVER: {{ gitea.url }}
      DRONE_GITEA_CLIENT_ID: {{ gitea.client_id }}
      DRONE_GITEA_CLIENT_SECRET: {{ gitea.client_secret }}
      # DRONE_GIT_ALWAYS_AUTH: "true"
