- name: "{{ domain.key }} volumes"
  ansible.builtin.include_tasks: volume.yml
  vars: { volume: "{{ item.volume }}" }
  when: item.type == 'volume'
  loop: "{{ domain.value.storage }}"
- name: "{{ domain.key }} definition"
  ansible.builtin.shell: |
    set -e
    before=$(virsh dumpxml {{ domain.key }})
    beforei=$(virsh dumpxml --inactive {{ domain.key }})
    virsh define <(echo '{{ lookup('template', 'domain.xml') }}')
    after=$(virsh dumpxml {{ domain.key }})
    afteri=$(virsh dumpxml --inactive {{ domain.key }})
    if [[ "$before" != "$after" ]]; then echo "domain definition changed"; fi
    if [[ "$beforei" != "$afteri" ]]; then echo "inactive domain definition changed"; fi
  args: { executable: bash }
  register: result
  changed_when: "'domain definition changed' in result.stdout"
