- name: package
  ansible.builtin.apt: { name: [libvirt-daemon-system, qemu-system], install_recommends: no }
- name: python bindings
  ansible.builtin.package: { name: [python3-libvirt, python3-lxml] }

- name: pools
  ansible.builtin.include_tasks: pool.yml
  loop: "{{ pools | dict2items }}"
- name: machine
  ansible.builtin.include_tasks: machine.yml
  loop: "{{ machines | dict2items }}"

# TODO: figure out backing storage configuration (recordsize, volume vs. file, raw vs. qcow2)
