- name: package
  ansible.builtin.apt: { name: [libvirt-daemon-system, qemu-system, dnsmasq-base, ovmf], install_recommends: no }
- name: python bindings
  ansible.builtin.package: { name: [python3-libvirt, python3-lxml] }

- name: pools
  ansible.builtin.include_tasks: pool.yml
  loop: "{{ pools | dict2items }}"
  loop_control: { loop_var: pool }
- name: domains
  ansible.builtin.include_tasks: domain.yml
  loop: "{{ domains | dict2items }}"
  loop_control: { loop_var: domain }

# TODO: figure out what domain options can be inferred by libvirt
# TODO: figure out backing storage configuration (recordsize, volume vs. file, raw vs. qcow2)
# TODO: what sort of settings does operating system selection affect? make templates for windows and linux?
