- name: package
  ansible.builtin.apt: { name: [libvirt-daemon-system, qemu-system], install_recommends: no }
- name: python bindings
  ansible.builtin.package: { name: [python3-libvirt, python3-lxml] }

- name: pools
  ansible.builtin.include_tasks: pool.yml
  loop: "{{ pools | dict2items }}"
  loop_control: { loop_var: pool }

# - name: machine
#   community.libvirt.virt:
#     name: host4
#     command: undefine
# - name: machine
#   community.libvirt.virt:
#     command: define
#     xml: "{{ lookup('template', 'host4.xml') }}"

# TODO: figure out backing storage configuration (recordsize, volume vs. file, raw vs. qcow2)
