- name: "{{ content.volume }} definition"
  ansible.builtin.command: virsh vol-create-as {{ content.pool }} {{ content.volume }} {{ content.size }}
  register: result
  failed_when: result.rc != 0 and 'exists already' not in result.stderr
  changed_when: result.rc == 0
