services:
  main:
    image: gitea/gitea
    restart: unless-stopped
    volumes: [./data:/data]
    ports:
    - {{ '{}:80:3000'.format(address) if address is defined else '80:3000' }}
    - {{ '{}:22:22'.format(address) if address is defined else '22:22' }}
    environment:
      GITEA____APP_NAME: {{ title }}
      GITEA__SECURITY__INSTALL_LOCK: "true"
      GITEA__SERVER__DOMAIN: {{ server.http }}
      GITEA__SERVER__SSH_DOMAIN: {{ server.ssh }}
      GITEA__SERVER__ROOT_URL: {{ server.url }}
{% if configuration is defined %}
{% for section, entries in configuration.items() %}
{% for name, value in entries.items() %}
      GITEA__{{ section }}__{{ name }}: "{{ value }}"
{% endfor %}
{% endfor %}
{% endif %}
