- name: packages
  ansible.builtin.apt:
    name:
    # libvirt
    - libvirt-daemon-system
    - libvirt-daemon-driver-lxc 
    - libvirt-daemon-driver-qemu # already installed by libvirt-daemon-system
    - dnsmasq-base # network server for virtual networks
    # lxc
    - lxc
    # qemu
    - qemu-system
    - qemu-utils # includes qemu-img, needed for non-raw images
    - ovmf # firmware for efi support
    install_recommends: no
- name: service
  ansible.builtin.systemd: { name: libvirtd, enabled: yes, state: started }
# - name: configuration
#   ansible.builtin.copy: { src: qemu.conf, dest: /etc/libvirt/qemu.conf }
#   notify: restart libvirtd
# - name: flush handlers
#   ansible.builtin.meta: flush_handlers

- name: users
  ansible.builtin.user: { name: "{{ item }}", groups: [libvirt], append: true }
  loop: "{{ users }}"

- name: pools
  ansible.builtin.include_tasks: pool.yml
  loop: "{{ pools | dict2items }}"
  loop_control: { loop_var: pool }
  when: pools is defined
- name: domains
  ansible.builtin.include_tasks: domain.yml
  loop: "{{ domains | dict2items }}"
  loop_control: { loop_var: domain }
  when: domains is defined
