- name: check
  ansible.builtin.stat: { path: "{{ path }}" }
  register: result
- name: allocate
  ansible.builtin.command: fallocate --length {{ size }} {{ path }}
  when: not result.stat.exists
- name: format
  ansible.builtin.command: mkswap {{ path }}
  when: not result.stat.exists
- name: mode
  ansible.builtin.file: { path: "{{ path }}", mode: 0600 }
- name: fstab
  ansible.builtin.lineinfile: { path: /etc/fstab, line: "{{ path }} none swap sw 0 0" }
- name: enable
  ansible.builtin.command: swapon {{ path }}
  register: result
  changed_when: result.rc == 0
