version: "3"

services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./entrypoint:/docker-entrypoint.d:ro
    - ./configuration:/etc/nginx/conf.d:ro
    - ./letsencrypt:/etc/letsencrypt:ro
    - ./webroot:/usr/share/nginx/html:ro
    ports:
    - {{ '{}:80:80'.format(address) if address is defined else '80:80' }}
    - {{ '{}:443:443'.format(address) if address is defined else '443:443' }}
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    depends_on: [nginx]
    volumes:
    - ./letsencrypt:/etc/letsencrypt
    - ./webroot:/webroot
