services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./entrypoint:/docker-entrypoint.d:ro
    - ./configuration:/etc/nginx/conf.d:ro
    - ./letsencrypt:/etc/letsencrypt:ro
    - ./webroot:/usr/share/nginx/html:ro
    network_mode: host
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    depends_on: [nginx]
    entrypoint: crond -f -d 8
    volumes:
    - ./daily:/etc/periodic/daily:ro
    - ./letsencrypt:/etc/letsencrypt
    - ./webroot:/webroot
