- name: package
  ansible.builtin.apt: { pkg: python3-requests }
- name: configuration
  ansible.builtin.template: { src: journal.json, dest: journal/ }
- name: script
  ansible.builtin.copy: { src: journal.py, dest: journal/ }
