version: "3"

services:
  main:
    # TODO: unfix once gitea adjust latest tag
    image: gitea/gitea:1.17.3
    restart: unless-stopped
    volumes: [./data:/data]
    ports:
    - {{ '{}:80:3000'.format(address) if address is defined else '80:3000' }}
    - {{ '{}:22:22'.format(address) if address is defined else '22:22' }}
    environment:
      GITEA____APP_NAME: {{ title }}
      GITEA__SECURITY__INSTALL_LOCK: "true"
      GITEA__SERVER__DOMAIN: {{ server.http }}
      GITEA__SERVER__SSH_DOMAIN: {{ server.ssh }}
      GITEA__SERVER__ROOT_URL: {{ server.url }}
      GITEA__SERVICE__DISABLE_REGISTRATION: "true"
      GITEA__INDEXER__REPO_INDEXER_ENABLED: "true"
      GITEA__REPOSITORY__DEFAULT_REPO_UNITS: repo.code
