- name: package
  ansible.builtin.apt: { name: [python3, python3-requests] }
- name: script
  ansible.builtin.copy: { src: jourdis.py, dest: /usr/local/sbin/, mode: 0755 }
  notify: restart jourdis
- name: configuration
  ansible.builtin.template: { src: jourdis.json, dest: /etc/, mode: 0600 }
  notify: restart jourdis
- name: service
  ansible.builtin.import_role: { name: tools/service }
  vars: { service: jourdis, description: journald discord notifications, command: jourdis.py, target: multi-user }
- name: service enabled
  ansible.builtin.systemd_service: { name: jourdis, enabled: yes, state: started, daemon_reload: yes }
- name: flush handlers
  ansible.builtin.meta: flush_handlers
