- name: package
  ansible.builtin.apt: { name: dnsmasq }
- name: service
  ansible.builtin.systemd: { name: dnsmasq, enabled: yes, state: started }
- name: configuration
  ansible.builtin.template: { src: dnsmasq.conf, dest: /etc/ }
  notify: restart dnsmasq
- name: flush handlers
  ansible.builtin.meta: flush_handlers
