- name: packages
  ansible.builtin.apt:
    name:
    - libvirt-daemon-system
    - qemu-system
    - qemu-utils
    - ovmf
    - dnsmasq-base
    install_recommends: no
- name: service
  ansible.builtin.systemd: { name: libvirtd, enabled: yes, state: started }

- name: pools
  ansible.builtin.include_tasks: pool.yml
  loop: "{{ pools | dict2items }}"
  loop_control: { loop_var: pool }
- name: domains
  ansible.builtin.include_tasks: domain.yml
  loop: "{{ domains | dict2items }}"
  loop_control: { loop_var: domain }
