- name: set
  ansible.builtin.hostname: { name: "{{ inventory_hostname }}" }
  when: ansible_os_family != "Windows"

- name: set
  ansible.windows.win_hostname: { name: "{{ inventory_hostname }}" }
  register: result
  when: ansible_os_family == "Windows"
- name: reboot
  ansible.windows.win_reboot:
  when: ansible_os_family == "Windows" and result.reboot_required
