- name: listen address
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ListenAddress \\d+\\.\\d+\\.\\d+\\.\\d+"
    line: "{{ 'ListenAddress {}'.format(system.address) if system.address is defined else '#ListenAddress 0.0.0.0' }}"
  notify: restart ssh

- name: directory
  ansible.builtin.file: { path: /root/.ssh, state: directory }
- name: authorized keys
  ansible.posix.authorized_key:
    user: root
    key: "ssh-ed25519 {{ item.value.key }} {{ item.key }}"
    key_options: "{{ item.value.options | join(',') if item.value.options is defined else omit }}"
  loop: "{{ authorized_keys | dict2items }}"
  when: authorized_keys is defined
- name: known hosts
  ansible.builtin.known_hosts: { name: "{{ item.key }}", key: "{{ item.key }} ssh-ed25519 {{ item.value }}" }
  loop: "{{ known_hosts | dict2items }}"
  when: known_hosts is defined
- name: private key
  ansible.builtin.template: { src: private_key, dest: /root/.ssh/id_ed25519, mode: 0600 }
  when: private_key is defined

- name: flush handlers
  ansible.builtin.meta: flush_handlers
