- name: system
  ansible.builtin.include_tasks: system.yml
- name: users
  ansible.builtin.include_tasks: user.yml
  loop: "{{ users | dict2items }}"
- name: flush handlers
  ansible.builtin.meta: flush_handlers
