- name: system
  ansible.builtin.include_tasks: system.yml
  when: system is defined
- name: users
  ansible.builtin.include_tasks: user.yml
  loop: "{{ users | dict2items }}"
  when: users is defined
- name: flush handlers
  ansible.builtin.meta: flush_handlers
