- name: package
  ansible.builtin.apt: { name: openssh-server }
  when: ansible_os_family == "Debian"
  # TODO: hopefully there will soon be a win_capability module
  #       https://github.com/ansible-collections/community.windows/issues/270
- name: capability
  win_shell: |
    $result = Get-WindowsCapability -Online -Name OpenSSH.Server | Where-Object State -EQ Installed
    if (!$result) { Add-WindowsCapability -Online -Name OpenSSH.Server }
  become: yes
  become_method: runas
  register: result
  changed_when: result.stdout != ""
  when: ansible_os_family == "Windows"

- name: service
  ansible.builtin.service: { name: ssh, enabled: yes, state: started }
  when: ansible_os_family == "Debian"

- name: system
  ansible.builtin.include_tasks: system.yml
  when: system is defined
- name: users
  ansible.builtin.include_tasks: user.yml
  loop: "{{ users | dict2items }}"
  loop_control: { loop_var: user }
  when: users is defined

- name: flush handlers
  ansible.builtin.meta: flush_handlers
