- name: listen address
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ListenAddress \\d+\\.\\d+\\.\\d+\\.\\d+"
    line: "{{ 'ListenAddress {}'.format(system.address) if system.address is defined else '#ListenAddress 0.0.0.0' }}"
  notify: restart ssh

- name: users
  ansible.builtin.include_tasks: user.yml
  loop: "{{ users | dict2items }}"

- name: flush handlers
  ansible.builtin.meta: flush_handlers
