- name: configuration
  ansible.builtin.template: { src: sshd.conf, dest: /etc/ssh/sshd_config.d/ }
  notify: restart ssh
- name: keys
  ansible.builtin.template: { src: private_key, dest: "/etc/ssh/{{ item.key }}", mode: 0600 }
  vars: { key: "{{ item.value }}" }
  loop: "{{ system['keys'] | dict2items }}"
  when: system['keys'] is defined
  notify: restart ssh
