- name: compose definition
  ansible.builtin.template: { src: docker-compose.yml, dest: "{{ path }}/" }
- name: compose up
  community.docker.docker_compose: { project_src: "{{ path }}" }

- name: default configuration
  ansible.builtin.copy: { src: default.conf, dest: "{{ path }}/configuration/" }
  notify: reload nginx service
- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: certificates
  ansible.builtin.include_tasks: certificate.yml
  loop: "{{ entries | dict2items }}"
  loop_control: { label: "{{ item.key }}" }

- name: flush handlers
  ansible.builtin.meta: flush_handlers
