- name: docker
  ansible.builtin.apt: { pkg: [docker.io, docker-compose] }
- name: certbot
  ansible.builtin.apt: { pkg: certbot }
- name: service configuration
  ansible.builtin.copy: { src: docker-compose.yml, dest: proxy/ }
- name: nginx configuration
  ansible.builtin.template: { src: proxy.conf, dest: proxy/configuration/ }
  notify: restart service
- name: service
  community.docker.docker_compose: { project_src: proxy }
