services:
  main:
    image: jellyfin/jellyfin
    restart: unless-stopped
    hostname: {{ inventory_hostname }}
    volumes:
    - ./config:/config
    - ./cache:/cache
{% for name, path in media.items() %}
    - {{ path }}:/media/{{ name }}:ro
{% endfor %}
    ports:
    - {{ forward.http | default(80) }}:8096
    - {{ forward.service | default(1900) }}:1900/udp
    - {{ forward.client | default(7359) }}:7359/udp
