- name: package
  ansible.builtin.apt: { pkg: samba }
- name: user share
  ansible.builtin.user: { name: share, create_home: false }
- name: users system
  ansible.builtin.user: { name: "{{ item.key }}", groups: [share], create_home: false, append: true }
  loop: "{{ samba.users | dict2items }}"
- name: users samba
  samba: { name: "{{ item.key }}", password: "{{ item.value.password }}" }
  loop: "{{ samba.users | dict2items }}"
- name: share directories
  ansible.builtin.file:
    path: "{{ item.value.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775
  vars: { user: "{{ item.value.users[0] if item.value.users | default | length == 1 else 'share' }}" }
  loop: "{{ samba.shares | dict2items }}"
- name: configuration
  ansible.builtin.template: { src: smb.conf, dest: /etc/samba/, validate: testparm --suppress-prompt %s }
  notify: restart samba
