- name: devices
  ansible.builtin.include_tasks: device.yml
  loop: "{{ devices | dict2items }}"
  loop_control: { loop_var: device, label: "{{ device.key }}" }
- name: swap
  ansible.builtin.command: swapon /dev/{{ item }}
  register: result
  failed_when: result.rc != 0 and 'Device or resource busy' not in result.stderr
  changed_when: result.rc == 0
  loop: "{{ swap }}"
- name: mount
  ansible.builtin.command: mount --onlyonce --mkdir /dev/{{ item.key }} /mnt{{ item.value }}
  register: result
  failed_when: result.rc != 0 and 'filesystem already mounted' not in result.stderr
  changed_when: result.rc == 0
  loop: "{{ mount | dict2items }}"
  loop_control: { label: "{{ item.key }}" }

- name: pacstrap
  ansible.builtin.shell:
    cmd: pacstrap -K /mnt {{ packages | join(' ') }} 1> /dev/tty1 2>&1
    creates: /mnt/etc/arch-release

- name: generate fstab
  ansible.builtin.command: genfstab -U /mnt
  register: result
  changed_when: false
- name: write fstab
  ansible.builtin.copy: { content: "{{ result.stdout }}", dest: /mnt/etc/fstab }
