- name: partition
  community.general.parted:
    device: /dev/{{ device.key }}
    label: gpt
    number: "{{ ansible_loop.index }}"
    flags: "{{ partition.flags | default(omit) }}"
    fs_type: "{{ filesystem[partition.filesystem] }}"
    part_start: "{{ partition.start }}"
    part_end: "{{ partition.end }}"
    state: present
  vars: { filesystem: { swap: linux-swap, vfat: fat32, ext4: ext4 } }
- name: filesystem
  community.general.filesystem:
    dev: /dev/{{ device.key }}{{ ansible_loop.index }}
    fstype: "{{ partition.filesystem }}"
