- name: partition
  community.general.parted:
    device: /dev/{{ device.key }}
    label: gpt
    number: "{{ ansible_loop.index }}"
    fs_type: "{{ partition.filesystem }}"
    part_start: "{{ partition.start }}"
    part_end: "{{ partition.end }}"
    flags: "{{ partition.flags | default(omit) }}"
    state: present
