- name: package
  ansible.builtin.apt: { name: samba }
- name: service
  ansible.builtin.systemd_service: { name: smbd, enabled: yes, state: started }
- name: users samba
  samba:
    name: "{{ item.key }}"
    nt_hash: "{{ item.value.hash | default(omit) }}"
    password: "{{ item.value.password | default(omit) }}"
  loop: "{{ users | dict2items }}"
  loop_control: { label: "{{ item.key }}" }
- name: configuration
  ansible.builtin.template: { src: smb.conf, dest: /etc/samba/, validate: testparm --suppress-prompt %s }
  notify: reload samba
- name: flush handlers
  ansible.builtin.meta: flush_handlers
