- name: users
  ansible.builtin.user:
    name: "{{ user.key }}"
    password: "{{ hash }}"
    update_password: on_create
  vars:
    salt: "{{ '%016x' % (2 ** 64) | random(seed = inventory_hostname + ':' + user.key) }}"
    hash: "{{ user.value.password | string | password_hash('sha512', salt) }}"
  loop: "{{ users | dict2items }}"
  loop_control: { loop_var: user }
