- name: docker package
  ansible.builtin.apt: { pkg: [docker.io, docker-compose] }
- name: docker compose definition
  ansible.builtin.copy: { src: docker-compose.yml, dest: "{{ path }}/" }
- name: docker compose up
  community.docker.docker_compose: { project_src: "{{ path }}" }

- name: administrator
  community.docker.docker_container_exec:
    container: gitea_main_1
    user: git
    command: >
      gitea admin user create
      --admin
      --username {{ admin.username }}
      --password {{ admin.password }}
      --email {{ admin.email }}
  vars:
    created: "New user '{{ admin.username }}' has been successfully created!"
    exists: "CreateUser: user already exists [name: {{ admin.username }}]"
  register: result
  failed_when: result.rc != 0 and exists not in result.stdout
  changed_when: result.rc == 0 and created in result.stdout
