- name: docker package
  ansible.builtin.apt: { pkg: [docker.io, docker-compose] }
- name: docker compose definition
  ansible.builtin.copy: { src: docker-compose.yml, dest: "{{ path }}/" }
- name: docker compose up
  community.docker.docker_compose: { project_src: "{{ path }}" }

- name: user
  community.docker.docker_container_exec:
    container: gitea_main_1
    user: 1000
    command: gitea admin user create --admin --username user1 --password password --email name@example.com
