- name: package
  ansible.builtin.package: { name: borgmatic }
- name: ssh directory
  ansible.builtin.file: { path: /root/.ssh, state: directory }
- name: ssh hosts
  ansible.builtin.known_hosts: { name: "{{ item.key }}", key: "{{ item.key }} ssh-ed25519 {{ item.value }}" }
  loop: "{{ hosts | dict2items }}"
- name: ssh key
  ansible.builtin.template: { src: id_ed25519, dest: /root/.ssh/, mode: 0600 }
- name: configuration
  ansible.builtin.template: { src: config.yaml, dest: /etc/borgmatic/, validate: validate-borgmatic-config --config %s }
- name: repository
  ansible.builtin.command: borgmatic init --encryption repokey
  environment: { BORG_PASSPHRASE: "{{ password }}" }
  register: result
  changed_when: result.stdout or result.stderr
