- name: package
  ansible.builtin.package: { name: borgmatic }
- name: key
  ansible.builtin.template: { src: ssh.key, dest: /root/.ssh/id_ed25519, mode: 0600 }
# - name: key pair
#   community.crypto.openssh_keypair: { path: /root/.ssh/id_ed25519, type: ed25519 }
- name: configuration
  ansible.builtin.template: { src: config.yaml, dest: /etc/borgmatic/, validate: validate-borgmatic-config --config %s }
