- name: package
  ansible.builtin.package: { name: borgmatic }
- name: directory
  ansible.builtin.file: { path: /etc/borgmatic.d, state: directory, mode: 0600 }
- name: configuration
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/borgmatic.d/{{ item.key }}.yaml
    validate: validate-borgmatic-config --config %s
  loop: "{{ backups | dict2items }}"

- name: repositories
  ansible.builtin.command: borgmatic init --encryption repokey
  register: result
  changed_when: result.stdout or result.stderr
- name: timer
  ansible.builtin.include_role: { name: system/timer }
  vars:
    service: borgmatic
    description: daily borgmatic backup
    command: borgmatic --verbosity -1 --syslog-verbosity 1 create --files --stats
    time: "{{ time }}"
    variance: 1h
    persistent: yes
- name: timer enabled
  ansible.builtin.systemd: { name: borgmatic.timer, enabled: yes, state: started, daemon_reload: yes }

# TODO: take care of ssh host key setup on new machine
# TODO: consider separate ssh user
# TODO: use ssh forced command
# TODO: use borg serve --append-only --restrict-to-path?
