- name: package
  ansible.builtin.package: { name: borgmatic }
- name: directory
  ansible.builtin.file: { path: /etc/borgmatic.d, state: directory, mode: 0600 }
- name: configuration
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/borgmatic.d/{{ item.key }}.yaml
    validate: validate-borgmatic-config --config %s
  loop: "{{ backups | dict2items }}"

- name: repositories
  ansible.builtin.command: borgmatic init --encryption repokey
  register: result
  changed_when: result.stdout or result.stderr
- name: notify script
  ansible.builtin.copy: { src: notify.py, dest: /usr/local/sbin/borgmatic-notify.py, mode: 0755 }
- name: notify configuration
  ansible.builtin.template: { src: notify.json, dest: /etc/borgmatic-notify.json, mode: 0600 }
- name: timer
  ansible.builtin.include_role: { name: system/timer }
  vars:
    service: borgmatic
    description: daily borgmatic backup
    command: borgmatic-notify.py
    time: "{{ timer }}"
    variance: 1h
    persistent: yes
- name: timer enabled
  ansible.builtin.systemd: { name: borgmatic.timer, enabled: yes, state: started, daemon_reload: yes }
