- name: package
  ansible.builtin.package: { name: borgmatic }
- name: directory
  ansible.builtin.file: { path: /etc/borgmatic.d, state: directory }
- name: configuration
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/borgmatic.d/{{ item.key }}.yaml
    validate: validate-borgmatic-config --config %s
  loop: "{{ archives | dict2items }}"
- name: repositories
  ansible.builtin.command: borgmatic init --encryption repokey
  register: result
  changed_when: result.stdout or result.stderr
