- name: package
  ansible.builtin.apt: { name: borgmatic }
- name: directory
  ansible.builtin.file: { path: /etc/borgmatic.d, state: directory, mode: 0600 }
- name: configuration
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/borgmatic.d/{{ item.key }}.yaml
    validate: validate-borgmatic-config --config %s
  loop: "{{ backups | dict2items }}"

- name: repositories
  ansible.builtin.command: borgmatic init --encryption repokey
  register: result
  changed_when: result.stdout or result.stderr

- name: timer
  ansible.builtin.include_role: { name: tools/timer }
  vars:
    service: borgmatic
    description: borgmatic backup
    command: borgmatic --verbosity -1 --syslog-verbosity 1 create
    time: "{{ timer | default('*-*-* 00:00:00') }}"
    variance: 1h
    persistent: yes
- name: timer enabled
  ansible.builtin.systemd: { name: borgmatic.timer, enabled: yes, state: started, daemon_reload: yes }
