- name: restart nginx service
  community.docker.docker_compose: { project_src: "{{ path }}", services: nginx, restarted: yes }
- name: reload nginx service
  community.docker.docker_container_exec: { container: proxy_nginx_1, command: nginx -s reload }
