# TODO: stop dhcpcd so it does not interfere with dnsmasq?
# TODO: what if we want an rpi to have dhcpcd? how can we make this a one-time thing?
# TODO: how can we properly switch from one IP to the permanent one?
# TODO: check contents of raspberrypi-net-mods
- name: plain network
  ansible.builtin.apt: { name: [dhcpcd, dhcpcd5, resolvconf, openresolv], state: absent, purge: yes, autoremove: yes }
  notify: reboot
