- name: package
  ansible.builtin.apt: { name: smartmontools }
- name: service
  ansible.builtin.systemd_service: { name: smartd, enabled: yes, state: started }
# TODO: in smartmontools 7.3 this can be set per-device in smartd.conf
#       this makes this configuration file and the restart handler obsolete
- name: configuration service
  ansible.builtin.template: { src: smartmontools, dest: /etc/default/ }
  notify: restart smart
- name: configuration daemon
  ansible.builtin.template: { src: smartd.conf, dest: /etc/ }
  notify: reload smart
- name: flush handlers
  ansible.builtin.meta: flush_handlers
