- name: package
  ansible.builtin.apt: { name: smartmontools }
- name: service
  ansible.builtin.systemd: { name: smartd, enabled: yes, state: started }
- name: configuration service
  ansible.builtin.template: { src: smartmontools, dest: /etc/default/ }
  notify: restart smart
- name: configuration daemon
  ansible.builtin.template: { src: smartd.conf, dest: /etc/ }
  notify: restart smart
- name: flush handlers
  ansible.builtin.meta: flush_handlers
