#!/bin/bash

export SMARTD_TIME=$(date -Iseconds -d @$SMARTD_TFIRSTEPOCH)
# TODO: this is too long to embed, use discord attachments
#export SMARTD_INFO=$(/usr/sbin/smartctl --all $SMARTD_DEVICE)

header="Content-Type: application/json"
data=$(envsubst <<< '{{ template | to_json }}')
data=${data//$'\n'/\\n}
data=${data//$'\t'/\\t}

#echo "$data" > /tmp/data.json

#curl --silent --header "$header" --data "$data" {{ url }}

/usr/sbin/smartctl --all $SMARTD_DEVICE > /tmp/smartctl.txt

curl --silent --form "payload_json=$data" --form "files[0]=@/tmp/smartctl.txt" {{ url }}
