version: "3"

services:
  main:
    image: drone/drone-runner-docker
    restart: unless-stopped
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    ports: [{{ '{}:3000:3000'.format(address) if address is defined else '3000:3000' }}]
    environment:
      DRONE_RUNNER_NAME: {{ runner.name }}
      DRONE_RUNNER_CAPACITY: {{ runner.capacity }}
      DRONE_RPC_PROTO: {{ server.protocol }}
      DRONE_RPC_HOST: {{ server.host }}
      DRONE_RPC_SECRET: {{ server.secret }}
