- name: packages
  ansible.builtin.apt: { name: bridge-utils }
- name: base
  ansible.builtin.copy: { src: interfaces.cfg, dest: /etc/network/interfaces }
  notify: restart networking
- name: loopback
  ansible.builtin.copy: { src: loopback.cfg, dest: /etc/network/interfaces.d/lo.cfg }
  notify: restart networking
- name: interfaces
  ansible.builtin.template: { src: interface.cfg, dest: "/etc/network/interfaces.d/{{ item.key }}.cfg" }
  loop: "{{ interfaces | dict2items }}"
  loop_control: { label: "{{ item.key }}" }
  notify: restart networking
- name: nameservers
  ansible.builtin.template: { src: resolv.conf, dest: /etc/ }
  when: nameservers is defined
- name: flush handlers
  ansible.builtin.meta: flush_handlers
