version: "3"

services:
  main:
    image: gitea/gitea
    restart: always
    volumes: [./data:/data]
    ports:
    - {{ address }}:80:80
    - {{ address }}:22:22
    environment:
      GITEA____APP_NAME: {{ title }}
      GITEA__SECURITY__INSTALL_LOCK: "true"
      GITEA__SERVER__PROTOCOL: http
      GITEA__SERVER__HTTP_PORT: 80
      GITEA__SERVER__DOMAIN: {{ server.http }}
      GITEA__SERVER__SSH_DOMAIN: {{ server.ssh }}
      GITEA__SERVER__ROOT_URL: {{ server.url }}
      GITEA__SERVICE__DISABLE_REGISTRATION: "true"
      GITEA__INDEXER__REPO_INDEXER_ENABLED: "true"
      GITEA__REPOSITORY__DEFAULT_REPO_UNITS: repo.code
