version: "3"

services:
  main:
    image: registry
    restart: unless-stopped
    volumes: [./data:/var/lib/registry]
    ports:
    - {{ '{}:5000:5000'.format(address) if address is defined else '5000:5000' }}
