version: "3"

services:
  main:
    image: jellyfin/jellyfin
    restart: unless-stopped
    hostname: {{ inventory_hostname }}
    volumes:
    - ./config:/config
    - ./cache:/cache
{% for target, path in media.items() %}
    - {{ path }}:/media/{{ target }}:ro
{% endfor %}
    ports:
    - {{ '{}:80:8096'.format(address) if address is defined else '80:8096' }}
