- name: "{{ pool.key }}/{{ volume.key }} check"
  ansible.builtin.command: virsh vol-info --pool {{ pool.key }} --vol {{ volume.key }}
  register: check
  failed_when: check.rc != 0 and 'Storage volume not found' not in check.stderr
  changed_when: "'Storage volume not found' in check.stderr"
- name: "{{ pool.key }}/{{ volume.key }} create"
  ansible.builtin.shell: virsh vol-create {{ pool.key }} <(echo '{{ lookup('template', 'volume.xml') }}')
  args: { executable: bash }
  when: check.changed
