- hosts: glados
  become: true
  roles:
  - role: system/hostname
  - role: system/users
    users:
      john: { password: "{{ people.john.password }}", groups: [sudo] }
      jack: { password: "{{ people.jack.password }}", groups: [sudo] }
      jill: { password: "{{ people.jill.password }}" }
  - role: system/ssh
    users:
      john: { authorized_keys: "{{ people.john.authorized_keys }}" }
      jack: { authorized_keys: "{{ people.jack.authorized_keys }}" }
  - role: system/apt

  - role: system/zfs
    pools:
      chell:
        scrub: yes
        properties: { ashift: 12 }
        vdevs:
        - raidz1: [vdb, vdc, vdd, vde]
    datasets:
      chell: { mountpoint: /mnt/chell, compression: lz4, atime: off, xattr: off }
      chell/services/gitea:
      chell/files: { recordsize: "1048576" }

  - role: services/docker

  - role: applications/gitea
    path: /mnt/chell/services/gitea
    title: Gitea
    server: { http: glados.local, ssh: glados.local, url: http://glados.local }
    admin: { username: john, password: "{{ people.john.password }}", email: john@example.com }
