- hosts: glados
  become: true
  roles:
  - role: system/hostname
  - role: system/users
    users:
      john: { password: qwerty, groups: [sudo] }
      jack: { password: asdfgh, groups: [sudo] }
      jill: { password: zxcvbn }
  - role: system/ssh
    users:
      john: { authorized_keys: { john: { type: ssh-ed25519, key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA } } }
      jack: { authorized_keys: { jack: { type: ssh-ed25519, key: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB } } }
  - role: system/apt
