- hosts: glados
  gather_facts: no
  serial: 1
  tasks:
  - import_role: { name: setup/debian }
    delegate_to: localhost
    vars:
      url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.6.0-amd64-netinst.iso
      directory: "{{ lookup('env', 'PWD') }}/preseed/"
      locale: { language: en, country: US, keymap: us }
      network: { hostname: glados }
      user: { name: john, password: "{{ people.john.password }}", authorized_keys: "{{ people.john.authorized_keys }}" }
      storage: { devices: [/dev/vda] }
      software: { sources: { contrib: true }, tasks: [standard, ssh-server] }
      exit: halt
