# TODO: can plugin installation be automated?
# TODO: can youtube keys be automated?
# TODO: fix fonts
- name: lightdm
  ansible.builtin.apt: { pkg: lightdm }
- name: kodi
  ansible.builtin.apt: { pkg: [kodi, kodi-inputstream-adaptive] }
- name: user
  #ansible.builtin.user: { name: kodi, create_home: false }
  ansible.builtin.user: { name: kodi }
- name: lightdm configuration
  ansible.builtin.copy: { src: lightdm.conf, dest: /etc/lightdm/ }
- name: youtube addon api keys
  ansible.builtin.copy: { src: api_keys.json, dest: .kodi/userdata/addon_data/plugin.video.youtube/ }
- name: jellyfin plugin
  ansible.builtin.unarchive:
    src: https://kodi.jellyfin.org/repository.jellyfin.kodi.zip
    dest: /home/kodi/.kodi/addons
    remote_src: true
