# TODO: fix fonts
- name: lightdm
  ansible.builtin.apt: { pkg: lightdm }
- name: kodi
  ansible.builtin.apt: { pkg: [kodi, kodi-inputstream-adaptive] }
- name: user
  ansible.builtin.user: { name: kodi }
- name: lightdm configuration
  ansible.builtin.copy: { src: lightdm.conf, dest: /etc/lightdm/ }

# kodi configuration
- name: repositories directory
  ansible.builtin.file:
    path: /home/kodi/.kodi/addons
    state: directory
    owner: kodi
    group: kodi
- name: jellyfin repository
  ansible.builtin.unarchive:
    src: https://kodi.jellyfin.org/repository.jellyfin.kodi.zip
    dest: /home/kodi/.kodi/addons/
    remote_src: true
    owner: kodi
    group: kodi
- name: youtube addon api keys
  ansible.builtin.template:
    src: api_keys.json
    dest: /home/kodi/.kodi/userdata/addon_data/plugin.video.youtube/
    owner: kodi
    group: kodi
