# TODO: can plugin installation be automated?
# TODO: can youtube keys be automated?
# TODO: fix fonts
# TODO: start kodi instead of gdm
- name: package
  ansible.builtin.apt: { pkg: [lightdm, kodi, kodi-inputstream-adaptive] }
- name: user
  #ansible.builtin.user: { name: kodi, create_home: false }
  ansible.builtin.user: { name: kodi }
- name: lightdm configuration
  ansible.builtin.copy: { src: lightdm.conf, dest: /etc/lightdm/ }
- name: jellyfin plugin
  ansible.builtin.get_url: { url: https://kodi.jellyfin.org/repository.jellyfin.kodi.zip, dest: . }
