- name: compose definition
  ansible.builtin.template: { src: docker-compose.yml, dest: "{{ path }}/" }
- name: compose up
  community.docker.docker_compose: { project_src: "{{ path }}" }
- name: configuration
  ansible.builtin.template: { src: ddclient.conf, dest: "{{ path }}/configuration/" }
