- name: package
  ansible.builtin.apt: { name: samba }
- name: service
  ansible.builtin.systemd: { name: smbd, enabled: yes, state: started }

- name: user share
  ansible.builtin.user: { name: share, create_home: false }
- name: users system
  ansible.builtin.user: { name: "{{ item.key }}", groups: [share], create_home: false, append: true }
  loop: "{{ users | dict2items }}"
- name: users samba
  samba:
    name: "{{ item.key }}"
    nt_hash: "{{ item.value.hash | default(omit) }}"
    password: "{{ item.value.password | default(omit) }}"
  loop: "{{ users | dict2items }}"

# TODO: samba should not be the one to manage users and directories, extract into TWO separate roles
# TODO: maybe ssh user configuration should also happen as part of the user role
- name: share directories
  ansible.builtin.file:
    path: "{{ item.value.path }}"
    state: directory
    owner: "{{ item.value.users[0] if single else 'share' }}"
    group: "{{ item.value.users[0] if single else 'share' }}"
    mode: "{{ '0755' if single else '02775' }}"
  vars: { single: "{{ item.value.users | default | length == 1 }}" }
  loop: "{{ shares | dict2items }}"

- name: configuration
  ansible.builtin.template: { src: smb.conf, dest: /etc/samba/, validate: testparm --suppress-prompt %s }
  notify: restart samba

- name: flush handlers
  ansible.builtin.meta: flush_handlers
