people:
  john:
    password: qwerty # better to use ansible vault
    authorized_keys: { john: { type: ssh-ed25519, key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA } }

ansible_password: "{{ people.john.password }}" # better to use ssh keys
ansible_become_password: "{{ people.john.password }}"
