- name: package
  ansible.builtin.apt: { pkg: zfsutils-linux }
- name: configuration
  ansible.builtin.template: { src: zfs.conf, dest: /etc/modprobe.d/ }
- name: kernel module
  community.general.modprobe: { name: zfs }
- name: pools
  zpool:
    name: "{{ item.key }}"
    vdevs: "{{ item.value.vdevs }}"
    properties: "{{ item.value.properties | default(omit) }}"
  loop: "{{ pools | dict2items }}"
- name: datasets
  community.general.zfs:
    name: "{{ item.key }}"
    state: present
    extra_zfs_properties: "{{ item.value | default(omit, true) }}"
  loop: "{{ datasets | dict2items }}"
  # TODO: use zfs-scrub-monthly timer shipped with zfs 2.1.3
- name: timer scrub install
  ansible.builtin.include_role: { name: systemd/timer-install }
  vars:
    service: zpool-scrub@
    description: zpool scrub on %i
    command: zpool scrub -w %i
    time: monthly
- name: timer scrub enable
  ansible.builtin.include_role: { name: systemd/timer-enable }
  vars:
    service: zpool-scrub@{{ item.key }}
    enabled: "{{ item.value.scrub | default(false) }}"
  loop: "{{ pools | dict2items }}"
  # TODO: use zfs-trim-monthly timer shipped with zfs x.x.x
- name: timer trim install
  ansible.builtin.include_role: { name: systemd/timer-install }
  vars:
    service: zpool-trim@
    description: zpool trim on %i
    command: zpool trim -w %i
    time: monthly
- name: timer trim enable
  ansible.builtin.include_role: { name: systemd/timer-enable }
  vars:
    service: zpool-trim@{{ item.key }}
    enabled: "{{ item.value.trim | default(false) }}"
  loop: "{{ pools | dict2items }}"
