- name: package
  ansible.builtin.apt: { pkg: python3-requests }
- name: script
  ansible.builtin.copy: { src: journal-notify.py, dest: /usr/local/sbin/, mode: 0755 }
- name: configuration
  ansible.builtin.template: { src: journal-notify.json, dest: /etc/, mode: 0600 }
